wandb_version: 1

_content:
  desc: null
  value:
    hyperparameters: '{''batch_size'': 64, ''batch_size_valid'': 500, ''lr'': 0.001,
      ''lr_optim'': 0.003, ''optimizer'': ''adam'', ''epochs'': 20, ''seed'': 123,
      ''data_path'': ''/Users/frederikhartmann/Desktop/3. Semester/Januar MLOPS/s2_cookiecutter_exercise/data/processed''}'
_flags_cache:
  desc: null
  value:
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=None, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2022-01-06'', (''%H-%M-%S'',): ''14-40-54''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1641476455
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
lr:
  desc: null
  value: 0.07156378864089497
optimizer:
  desc: null
  value: sgd
